<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preload" as="style" href="/CSS/styles.css">
  <link rel="stylesheet" href="/CSS/styles.css">
  <meta name="description" content="Modern illustrated translation of the Revelation — Chapter 21">
  <title>Revelation Translation — Chapter 21</title>

  <?php include('../header.php'); ?>
  
</head>

<div align="center">
  <h1>Ἀποκάλυψις Ἰωάννου — κεφάλαιον κα’</h1>
  <h3 style="margin-bottom: 0px;">Revelation of John — #21</h3>

  <ul class="menu">
    <li class="menu"><a href="chapter20.php">Previous</li>
    <li class="menu"><a href="chapter22.php">Next</a></li>
  </ul>

  <i>May 2021</i>
  <br><br>
  <img src="/media/imgs/GNT/revtrans/newjerusalem.webp", width="200", height="200" onerror="this.onerror=null; this.src='/media/imgs/GNT/revtrans/newjerusalem.jpg'" alt="" width="200" height="200">
  <br>
  <i>John being shown the New Jerusalem — 1636 – 1637, Alonso Cano</i>
</div>

<div class="row">
  <div class="column">
    <div class="article">
      <p>Καὶ εἶδον οὐρανὸν καινὸν καὶ γῆν καινήν· ὁ γὰρ πρῶτος οὐρανὸς καὶ ἡ πρώτη γῆ παρῆλθε, καὶ ἡ θάλασσα οὐκ ἔστιν ἔτι. <sup>2</sup>καὶ ἐγὼ Ἰωάννης εἶδον τὴν πόλιν τὴν ἁγίαν, Ἰερουσαλὴμ καινήν, καταβαίνουσαν ἀπὸ τοῦ Θεοῦ ἐκ τοῦ οὐρανοῦ, ἡτοιμασμένην ὡς νύμφην κεκοσμημένην τῷ ἀνδρὶ αὐτῆς. <sup>3</sup>καὶ ἤκουσα φωνῆς μεγάλης ἐκ τοῦ οὐρανοῦ, λεγούσης, Ἰδού, ἡ σκηνὴ τοῦ Θεοῦ μετὰ τῶν ἀνθρώπων, καὶ σκηνώσει μετ’ αὐτῶν, καὶ αὐτοὶ λαοὶ αὐτοῦ ἔσονται, καὶ αὐτὸς ὁ Θεὸς ἔσται μετ’ αὐτῶν, Θεὸς αὐτῶν· <sup>4</sup>καὶ ἐξαλείψει ὁ Θεὸς πᾶν δάκρυον ἀπὸ τῶν ὀφθαλμῶν αὐτῶν, καὶ ὁ θάνατος οὐκ ἔσται ἔτι· οὔτε πένθος, οὔτε κραυγή, οὔτε πόνος οὐκ ἔσται ἔτι· ὅτι τὰ πρῶτα ἀπῆλθον. <sup>5</sup>καὶ εἶπεν ὁ καθήμενος ἐπὶ τοῦ θρόνου, Ἰδού, καινὰ πάντα ποιῶ. καὶ λέγει μοι, Γράψον· ὅτι οὗτοι οἱ λόγοι ἀληθινοὶ καὶ πιστοί εἰσι. <sup>6</sup>καὶ εἶπέ μοι, Γέγονε. ἐγώ εἰμι τὸ Α καὶ τὸ Ω, ἡ ἀρχὴ καὶ τὸ τέλος. ἐγὼ τῷ διψῶντι δώσω ἐκ τῆς πηγῆς τοῦ ὕδατος τῆς ζωῆς δωρεάν. <sup>7</sup>ὁ νικῶν κληρονομήσει τὰ πάντα, καὶ ἔσομαι αὐτῷ Θεός, καὶ αὐτὸς ἔσται μοι ὁ υἱός. <sup>8</sup>δειλοῖς δὲ καὶ ἀπίστοις καὶ ἐβδελυγμένοις καὶ φονεῦσι καὶ πόρνοις καὶ φαρμακεῦσι καὶ εἰδωλολάτραις, καὶ πᾶσι τοῖς ψευδέσι, τὸ μέρος αὐτῶν ἐν τῇ λίμνῃ τῇ καιομένῃ ἐν πυρὶ καὶ θείῳ, ὅ ἐστι δεύτερος θάνατος.</p>

      <p><sup>9</sup>Καὶ ἦλθεν πρός με εἷς ἐκ τῶν ἑπτὰ ἀγγέλων τῶν ἐχόντων τὰς ἑπτὰ φιάλας τὰς γεμούσας τῶν ἑπτὰ πληγῶν τῶν ἐσχάτων, καὶ ἐλάλησε μετ’ ἐμοῦ, λέγων, Δεῦρο, δείξω σοι τὴν νύμφην τοῦ ἀρνίου τὴν γυναῖκα. <sup>10</sup>καὶ ἀπήνεγκέ με ἐν Πνεύματι ἐπ’ ὄρος μέγα καὶ ὑψηλόν, καὶ ἔδειξέ μοι τὴν πόλιν τὴν μεγάλην, τὴν ἁγίαν Ἰερουσαλήμ, καταβαίνουσαν ἐκ τοῦ οὐρανοῦ ἀπὸ τοῦ Θεοῦ, <sup>11</sup>ἔχουσαν τὴν δόξαν τοῦ Θεοῦ· καὶ ὁ φωστὴρ αὐτῆς ὅμοιος λίθῳ τιμιωτάτῳ, ὡς λίθῳ ἰάσπιδι κρυσταλλίζοντι· <sup>12</sup>ἔχουσάν τε τεῖχος μέγα καὶ ὑψηλόν, ἔχουσαν πυλῶνας δώδεκα, καὶ ἐπὶ τοῖς πυλῶσιν ἀγγέλους δώδεκα, καὶ ὀνόματα ἐπιγεγραμμένα, ἅ ἐστι τῶν δώδεκα φυλῶν τῶν υἱῶν Ἰσραήλ. <sup>13</sup>ἀπ’ ἀνατολῆς, πυλῶνες τρεῖς· ἀπὸ βορρᾶ, πυλῶνες τρεῖς· ἀπὸ νότου, πυλῶνες τρεῖς· καὶ ἀπὸ δυσμῶν, πυλῶνες τρεῖς. <sup>14</sup>καὶ τὸ τεῖχος τῆς πόλεως ἔχον θεμελίους δώδεκα, καὶ ἐν αὐτοῖς ὀνόματα τῶν δώδεκα ἀποστόλων τοῦ ἀρνίου. <sup>15</sup>καὶ ὁ λαλῶν μετ’ ἐμοῦ εἶχε κάλαμον χρυσοῦν, ἵνα μετρήσῃ τὴν πόλιν, καὶ τοὺς πυλῶνας αὐτῆς, καὶ τὸ τεῖχος αὐτῆς. <sup>16</sup>καὶ ἡ πόλις τετράγωνος κεῖται, καὶ τὸ μῆκος αὐτῆς τοσοῦτόν ἐστιν ὄσον καὶ τὸ πλάτος. καὶ ἐμέτρησε τὴν πόλιν τῷ καλάμῳ ἐπὶ σταδίων δώδεκα χιλιάδων· τὸ μῆκος καὶ τὸ πλάτος καὶ τὸ ὕψος αὐτῆς ἴσα ἐστί. <sup>17</sup>καὶ ἐμέτρησε τὸ τεῖχος αὐτῆς ἑκατὸν τεσσαρακοντατεσσάρων πηχῶν, μέτρον ἀνθρώπου, ὅ ἐστιν ἀγγέλου· <sup>18</sup>καὶ ἦν ἡ ἐνδόμησις τοῦ τείχους αὐτῆς, ἴασπις· καὶ ἡ πόλις χρυσίον καθαρόν, ὁμοία ὑάλῳ καθαρῷ. <sup>19</sup>καὶ οἱ θεμέλιοι τοῦ τείχους τῆς πόλεως παντὶ λίθῳ τιμίῳ κεκοσμημένοι· ὁ θεμέλιος ὁ πρῶτος ἴασπις· ὁ δεύτερος, σάπφειρος· ὁ τρίτος, χαλκηδών, ὁ τέταρτος, σμάραγδος· <sup>20</sup>ὁ πέμπτος, σαρδόνυξ· ὁ ἕκτος, σάρδιον· ὁ ἕβδομος, χρυσόλιθος· ὁ ὄγδοος, βήρυλλος· ὁ ἔννατος, τοπάζιον· ὁ δέκατος, χρυσόπρασος· ὁ ἑνδέκατος, ὑάκινθος· ὁ δωδέκατος, ἀμέθυστος. <sup>21</sup>καὶ οἱ δώδεκα πυλῶνες, δώδεκα μαργαρῖται· ἀνὰ εἷς ἕκαστος τῶν πυλώνων ἦν ἐξ ἑνὸς μαργαρίτου· καὶ ἡ πλατεῖα τῆς πόλεως χρυσίον καθαρόν, ὡς ὕαλος διαφανής. <sup>22</sup>καὶ ναὸν οὐκ εἶδον ἐν αὐτῇ· ὁ γὰρ Κύριος ὁ Θεὸς ὁ παντοκράτωρ ναὸς αὐτῆς ἐστί, καὶ τὸ ἀρνίον. <sup>23</sup>καὶ ἡ πόλις οὐ χρείαν ἔχει τοῦ ἡλίου, οὐδὲ τῆς σελήνης, ἵνα φαίνωσιν ἐν αὐτῇ· ἡ γὰρ δόξα τοῦ Θεοῦ ἐφώτισεν αὐτήν, καὶ ὁ λύχνος αὐτῆς τὸ ἀρνίον. <sup>24</sup>καὶ τὰ ἔθνη τῶν σωζωμένων ἐν τῷ φωτὶ αὐτῆς περιπατήσουσι· καὶ οἱ βασιλεῖς τῆς γῆς φέρουσι τὴν δόξαν καὶ τὴν τιμὴν αὐτῶν εἰς αὐτήν. <sup>25</sup>καὶ οἱ πυλῶνες αὐτῆς οὐ μὴ κλεισθῶσιν ἡμέρας (νὺξ γὰρ οὐκ ἔσται ἐκεῖ)· <sup>26</sup>καὶ οἴσουσι τὴν δόξαν καὶ τὴν τιμὴν τῶν ἐθνῶν εἰς αὐτήν. <sup>27</sup>καὶ οὐ μὴ εἰσέλθῃ εἰς αὐτὴν πᾶν κοινοῦν, καὶ ποιοῦν βδέλυγμα καὶ ψεῦδος· εἰ μὴ οἱ γεγραμμένοι ἐν τῷ βιβλίῳ τῆς ζωῆς τοῦ ἀρνίου. XXIΙ. καὶ ἔδειξέ μοι καθαρὸν ποταμὸν ὕδατος ζωῆς, λαμπρὸν ὡς κρύσταλλον, ἐκπορευόμενον ἐκ τοῦ θρόνου τοῦ Θεοῦ καὶ τοῦ ἀρνίου.</p>
    </div>
  </div>

  <div class="column">
    <div class="article">
      <p>Kai eidon ouranon kainon kai gēn kainēn; ho gar prōtos ouranos kai hē prōtē gē parēlthe, kai hē thalassa ouk estin eti. <sup>2</sup>kai egō Iōannēs eidon tēn polin tēn hagian, Ierousalēm kainēn, katabainousan apo tou Theou ek tou ouranou, hētoimasmenēn hōs nymphēn kekosmēmenēn tō andri autēs. <sup>3</sup>kai ēkousa phōnēs megalēs ek tou ouranou, legousēs, Idou, hē skēnē tou Theou meta tōn anthrōpōn, kai skēnōsei met’ autōn, kai autoi laoi autou esontai, kai autos ho Theos estai met’ autōn, Theos autōn; <sup>4</sup>kai exaleipsei ho Theos pan dakryon apo tōn ophthalmōn autōn, kai ho thanatos ouk estai eti; oute penthos, oute kraugē, oute ponos ouk estai eti; hoti ta prōta apēlthon. <sup>5</sup>kai eipen ho kathēmenos epi tou thronou, Idou, kaina panta poiō. kai legei moi, Grapson; hoti houtoi hoi logoi alēthinoi kai pistoi eisi. <sup>6</sup>kai eipe moi, Gegone. egō eimi to A kai to Ō, hē archē kai to telos. egō tō dipsōnti dōsō ek tēs pēgēs tou hydatos tēs zōēs dōrean. <sup>7</sup>ho nikōn klēronomēsei ta panta, kai esomai autō Theos, kai autos estai moi ho huios. <sup>8</sup>deilois de kai apistois kai ebdelygmenois kai phoneusi kai pornois kai pharmakeusi kai eidōlolatrais, kai pasi tois pseudesi, to meros autōn en tē limnē tē kaiomenē en pyri kai theiō, ho esti deuteros thanatos.</p>

      <p><sup>9</sup>Kai ēlthen pros me heis ek tōn hepta angelōn tōn echontōn tas hepta phialas tas gemousas tōn hepta plēgōn tōn eschatōn, kai elalēse met’ emou, legōn, Deuro, deixō soi tēn nymphēn tou arniou tēn gynaika. <sup>10</sup>kai apēnenke me en Pneumati ep’ oros mega kai hypsēlon, kai edeixe moi tēn polin tēn megalēn, tēn hagian Ierousalēm, katabainousan ek tou ouranou apo tou Theou, <sup>11</sup>echousan tēn doxan tou Theou; kai ho phōstēr autēs homoios lithō timiōtatō, hōs lithō iaspidi krystallizonti; <sup>12</sup>echousan te teichos mega kai hypsēlon, echousan pylōnas dōdeka, kai epi tois pylōsin angelous dōdeka, kai onomata epigegrammena, ha esti tōn dōdeka phylōn tōn huiōn Israēl. <sup>13</sup>ap’ anatolēs, pylōnes treis; apo borra, pylōnes treis; apo notou, pylōnes treis; kai apo dysmōn, pylōnes treis. <sup>14</sup>kai to teichos tēs poleōs echon themelious dōdeka, kai en autois onomata tōn dōdeka apostolōn tou arniou. <sup>15</sup>kai ho lalōn met’ emou eiche kalamon chrysoun, hina metrēsē tēn polin, kai tous pylōnas autēs, kai to teichos autēs. <sup>16</sup>kai hē polis tetragōnos keitai, kai to mēkos autēs tosouton estin oson kai to platos. kai emetrēse tēn polin tō kalamō epi stadiōn dōdeka chiliadōn; to mēkos kai to platos kai to hypsos autēs isa esti. <sup>17</sup>kai emetrēse to teichos autēs hekaton tessarakontatessarōn pēchōn, metron anthrōpou, ho estin angelou; <sup>18</sup>kai ēn hē endomēsis tou teichous autēs, iaspis; kai hē polis chrysion katharon, homoia hyalō katharō. <sup>19</sup>kai hoi themelioi tou teichous tēs poleōs panti lithō timiō kekosmēmenoi; ho themelios ho prōtos iaspis; ho deuteros, sappheiros; ho tritos, chalkēdōn, ho tetartos, smaragdos; <sup>20</sup>ho pemptos, sardonyx; ho hektos, sardion; ho hebdomos, chrysolithos; ho ogdoos, bēryllos; ho ennatos, topazion; ho dekatos, chrysoprasos; ho hendekatos, hyakinthos; ho dōdekatos, amethystos. <sup>21</sup>kai hoi dōdeka pylōnes, dōdeka margaritai; ana heis hekastos tōn pylōnōn ēn ex henos margaritou; kai hē plateia tēs poleōs chrysion katharon, hōs hyalos diaphanēs. <sup>22</sup>kai naon ouk eidon en autē; ho gar Kyrios ho Theos ho pantokratōr naos autēs esti, kai to arnion. <sup>23</sup>kai hē polis ou chreian echei tou hēliou, oude tēs selēnēs, hina phainōsin en autē; hē gar doxa tou Theou ephōtisen autēn, kai ho lychnos autēs to arnion. <sup>24</sup>kai ta ethnē tōn sōzōmenōn en tō phōti autēs peripatēsousi; kai hoi basileis tēs gēs pherousi tēn doxan kai tēn timēn autōn eis autēn. <sup>25</sup>kai hoi pylōnes autēs ou mē kleisthōsin hēmeras (nyx gar ouk estai ekei); <sup>26</sup>kai oisousi tēn doxan kai tēn timēn tōn ethnōn eis autēn. <sup>27</sup>kai ou mē eiselthē eis autēn pan koinoun, kai poioun bdelygma kai pseudos; ei mē hoi gegrammenoi en tō bibliō tēs zōēs tou arniou. XXII. kai edeixe moi katharon potamon hydatos zōēs, lampron hōs krystallon, ekporeuomenon ek tou thronou tou Theou kai tou arniou.</p>
    </div>
  </div>

  <div class="column">
    <div class="article">
      <p>And I saw a new Heaven and a new Earth; for the first Heaven and the first Earth have departed (left) and the sea is no more. And the new holy city (of) Jerusalem I saw descending out of Heaven from God (and it was) prepared as a bride (is) for her husband (man). And I heard a great voice from the throne saying, “Behold! The tabernacle (tent) of God (is?) with the humans and He will live with them and they will be His people; and God himself will be with them. And He will wipe away every tear from their eyes and there will no longer be either death nor mourning nor weeping nor pains (toils, hardship) — for the first things have departed (gone away, left). </p>

      <p>And He who sits upon the throne said, “Behold! I make everything new (all things new).” And He says, “Write that (because?) these words are faithful and true.” And He said to me, “They (i. e. these things) have (now) happened (it is done). I am the Alpha and the Omega, the beginning and the end. I shall give the thirsty from the spring (fountain) of water of life freely. The victor shall inherit (all) this and I will be God to him and he will be a son to Me. But to the fearful (cowardly) and unbelieving and detestable (abominable) and murders and those who are sexually immoral; and (to) the sorcerers and those worshipping idols and to every liar: their part is in the lake burning with fire and brimstone (sulphur), which is the second death.”</p>

      <p>And there came (forth) one of the seven angels — the ones having the seven vials filled with the last seven plagues —and he spoke to me saying, “Come. I will show you the wife — the woman — of the Lamb.” And he carried me away in Spirit onto a great and high mountain; and he showed me the holy city Jerusalem — (the one) having the glory of God — descending out of Heaven from God. (And) its splendour was akin to (that of) a precious stone, (or) like (that of) crystal clear piece of jasper. </p>

      <p>And it had a great and tall wall, and it had twelve gates and upon the gates (there were) twelve angels and names (were) inscribed (upon them), (namely the names) which are (those) of the twelve tribes of Israel — three gates in the West(ern) part, three gates in the North(ern) part, three gates in the South(ern) part and three gates in the West(ern) part. And the city’s wall had twelve foundations and (written) upon them were the twelve names of the apostles of the Lamb. </p>

      <p>And (whilst he was) speaking to me, he had (in his hands) a golden measuring rod so that he may measure the city and its gates and its wall. And the city is laid (out as a) square and its length is as great as its breadth. And he measured the city with the rod at twelve-thousand stadia (roughly 2,100 km); its length and its breadth and its height are equal (in length). And he measured its wall at one-hundred forty-four cubits (roughly 72 m), the measure of a man, which is of the angel. And the material (out) of (which) the wall (was built) was jasper and the city was (made out of) pure gold, as a fine crystal. </p>

      <p>And the foundations of the wall were adorned with all (kinds of) precious stones: the first foundation is (made out of) jasper, the second is (made out of) sapphire, the third is (made out of) chalcedony, the fourth is (made out of) emerald, the fifth is (made out of) sardonyx, the sixth is (made out of) carnelian, the seventh is (made out of) chrysolite, the eight is (made out of) beryl, the ninth is (made out of) topaz, the tenth is (made out of) chrysoprase, the eleventh is (made out of) jacinth, and the twelfth is (made out of) amethyst. And the twelve gates are twelve pearls (and) each of the gates was (made out) of one (of the) pearls. And the street of the city (is made of) pure gold, like a transparent crystal.</p>

      <p>And I did not see any people in it, for the Lord God — the Almighty — is its people, and (so is) the Lamb. And the city has no need for the Sun, nor for the Moon, so that they may shine in it. For the glory of God illuminated it, and its lamp is the Lamb. And the nations will walk (through the city) through its (because of its) light, and the kings of the Earth carry their glory into it. And its gates may not be shut during the day, for there shall not be any night there. And they shall bring the glory and honour of the nations into it. And no unclean person nor any liar or person who does detestable things may enter it, except for the ones who are written in the Lamb’s book of life. </p>
    </div>
  </div>
</div>
</body>

<footer>
<?php include($_SERVER['DOCUMENT_ROOT'].'/footer.php'); ?>
</html>
