<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preload" as="style" href="/CSS/styles.css">
  <link rel="stylesheet" href="/CSS/styles.css">
  <script defer data-domain="ancient-greek.net" src="https://analytics.ancient-greek.net/js/plausible.js"></script>
  <meta name="description" content="Modern illustrated translation of the Gospel of John — Chapter 4">
  <title>Gospel of John Translation — Chapter 4</title>

  <?php include('../header.php'); ?>
</head>
<body>

<div align="center">
  <h1>Τὸ εὐαγγέλιον κατὰ Ἰωάννην — κεφάλαιον δ’</h1>
  <h3 style="margin-bottom: 0px;">Gospel of John — #4</h3>

  <ul class="menu">
    <li class="menu"><a href="chapter3.php">Previous</a></li>
    <li class="menu"><a href="chapter5.php">Next</a></li>
  </ul>

  <i>December 2021</i>
  <br><br>
</div>

<div class="row">
  <div class="column">
    <div class="article">
    <p>Ὡς οὖν ἔγνω ὁ Κύριος ὅτι ἤκουσαν οἱ Φαρισαῖοι ὅτι Ἰησοῦς πλείονας μαθητὰς ποιεῖ καὶ βαπτίζει ἢ Ἰωάνης, —καίτοιγε Ἰησοῦς αὐτὸς οὐκ ἐβάπτιζεν ἀλλ’ οἱ μαθηταὶ αὐτοῦ, — ἀφῆκεν τὴν Ἰουδαίαν καὶ ἀπῆλθεν πάλιν εἰς τὴν Γαλιλαίαν. Ἔδει δὲ αὐτὸν διέρχεσθαι διὰ τῆς Σαμαρίας. ἔρχεται οὖν εἰς πόλιν τῆς Σαμαρίας λεγομένην Συχὰρ, πλησίον τοῦ χωρίου ὃ ἔδωκεν Ἰακὼβ Ἰωσὴφ τῷ υἱῷ αὐτοῦ· ἦν δὲ ἐκεῖ πηγὴ τοῦ Ἰακώβ. ὁ οὖν Ἰησοῦς κεκοπιακὼς ἐκ τῆς ὁδοιπορίας ἐκαθέζετο οὕτως ἐπὶ τῇ πηγῇ· ὥρα ἦν ὡς ἕκτη. </p>

    <p>ἔρχεται γυνὴ ἐκ τῆς Σαμαρίας ἀντλῆσαι ὕδωρ. λέγει αὐτῇ ὁ Ἰησοῦς Δός μοι πεῖν. οἱ γὰρ μαθηταὶ αὐτοῦ ἀπεληλύθεισαν εἰς τὴν πόλιν, ἵνα τροφὰς ἀγοράσωσιν. λέγει οὖν αὐτῷ ἡ γυνὴ ἡ Σαμαρεῖτις Πῶς σὺ Ἰουδαῖος ὢν παρ’ ἐμοῦ πεῖν αἰτεῖς γυναικὸς Σαμαρείτιδος οὔσης; οὐ γὰρ συνχρῶνται Ἰουδαῖοι Σαμαρείταις. ἀπεκρίθη Ἰησοῦς καὶ εἶπεν αὐτῇ Εἰ ᾔδεις τὴν δωρεὰν τοῦ Θεοῦ, καὶ τίς ἐστιν ὁ λέγων σοι Δός μοι πεῖν, σὺ ἂν ᾔτησας αὐτὸν καὶ ἔδωκεν ἄν σοι ὕδωρ ζῶν. λέγει αὐτῷ Κύριε, οὔτε ἄντλημα ἔχεις καὶ τὸ φρέαρ ἐστὶν βαθύ· πόθεν οὖν ἔχεις τὸ ὕδωρ τὸ ζῶν; μὴ σὺ μείζων εἶ τοῦ πατρὸς ἡμῶν Ἰακώβ, ὃς ἔδωκεν ἡμῖν τὸ φρέαρ, καὶ αὐτὸς ἐξ αὐτοῦ ἔπιεν καὶ οἱ υἱοὶ αὐτοῦ καὶ τὰ θρέμματα αὐτοῦ; ἀπεκρίθη Ἰησοῦς καὶ εἶπεν αὐτῇ Πᾶς ὁ πίνων ἐκ τοῦ ὕδατος τούτου διψήσει πάλιν· ὃς δ’ ἂν πίῃ ἐκ τοῦ ὕδατος οὗ ἐγὼ δώσω αὐτῷ, οὐ μὴ διψήσει εἰς τὸν αἰῶνα, ἀλλὰ τὸ ὕδωρ ὃ δώσω αὐτῷ γενήσεται ἐν αὐτῷ πηγὴ ὕδατος ἁλλομένου εἰς ζωὴν αἰώνιον. λέγει πρὸς αὐτὸν ἡ γυνή Κύριε, δός μοι τοῦτο τὸ ὕδωρ, ἵνα μὴ διψῶ μηδὲ διέρχωμαι ἐνθάδε ἀντλεῖν. </p>

    <p>λέγει αὐτῇ Ὕπαγε φώνησον τὸν ἄνδρα σου καὶ ἐλθὲ ἐνθάδε. ἀπεκρίθη ἡ γυνὴ καὶ εἶπεν Οὐκ ἔχω ἄνδρα. λέγει αὐτῇ ὁ Ἰησοῦς Καλῶς εἶπες ὅτι Ἄνδρα οὐκ ἔχω· πέντε γὰρ ἄνδρας ἔσχες, καὶ νῦν ὃν ἔχεις οὐκ ἔστιν σου ἀνήρ· τοῦτο ἀληθὲς εἴρηκας. λέγει αὐτῷ ἡ γυνή Κύριε, θεωρῶ ὅτι προφήτης εἶ σύ. οἱ πατέρες ἡμῶν ἐν τῷ ὄρει τούτῳ προσεκύνησαν· καὶ ὑμεῖς λέγετε ὅτι ἐν Ἱεροσολύμοις ἐστὶν ὁ τόπος ὅπου προσκυνεῖν δεῖ. λέγει αὐτῇ ὁ Ἰησοῦς Πίστευέ μοι, γύναι, ὅτι ἔρχεται ὥρα ὅτε οὔτε ἐν τῷ ὄρει τούτῳ οὔτε ἐν Ἱεροσολύμοις προσκυνήσετε τῷ Πατρί. ὑμεῖς προσκυνεῖτε ὃ οὐκ οἴδατε, ἡμεῖς προσκυνοῦμεν ὃ οἴδαμεν, ὅτι ἡ σωτηρία ἐκ τῶν Ἰουδαίων ἐστίν· ἀλλὰ ἔρχεται ὥρα καὶ νῦν ἐστιν, ὅτε οἱ ἀληθινοὶ προσκυνηταὶ προσκυνήσουσιν τῷ Πατρὶ ἐν πνεύματι καὶ ἀληθείᾳ· καὶ γὰρ ὁ Πατὴρ τοιούτους ζητεῖ τοὺς προσκυνοῦντας αὐτόν· Πνεῦμα ὁ Θεός, καὶ τοὺς προσκυνοῦντας ἐν πνεύματι καὶ ἀληθείᾳ δεῖ προσκυνεῖν. λέγει αὐτῷ ἡ γυνή Οἶδα ὅτι Μεσσίας ἔρχεται, ὁ λεγόμενος Χριστός· ὅταν ἔλθῃ ἐκεῖνος, ἀναγγελεῖ ἡμῖν ἅπαντα. λέγει αὐτῇ ὁ Ἰησοῦς Ἐγώ εἰμι, ὁ λαλῶν σοι. </p>

    <p>Καὶ ἐπὶ τούτῳ ἦλθαν οἱ μαθηταὶ αὐτοῦ, καὶ ἐθαύμαζον ὅτι μετὰ γυναικὸς ἐλάλει· οὐδεὶς μέντοι εἶπεν Τί ζητεῖς ἢ τί λαλεῖς μετ’ αὐτῆς; ἀφῆκεν οὖν τὴν ὑδρίαν αὐτῆς ἡ γυνὴ καὶ ἀπῆλθεν εἰς τὴν πόλιν, καὶ λέγει τοῖς ἀνθρώποις Δεῦτε ἴδετε ἄνθρωπον ὃς εἶπέν μοι πάντα ἃ ἐποίησα· μήτι οὗτός ἐστιν ὁ Χριστός; ἐξῆλθον ἐκ τῆς πόλεως καὶ ἤρχοντο πρὸς αὐτόν. Ἐν τῷ μεταξὺ ἠρώτων αὐτὸν οἱ μαθηταὶ λέγοντες Ῥαββεί, φάγε. ὁ δὲ εἶπεν αὐτοῖς Ἐγὼ βρῶσιν ἔχω φαγεῖν ἣν ὑμεῖς οὐκ οἴδατε. ἔλεγον οὖν οἱ μαθηταὶ πρὸς ἀλλήλους Μή τις ἤνεγκεν αὐτῷ φαγεῖν; λέγει αὐτοῖς ὁ Ἰησοῦς Ἐμὸν βρῶμά ἐστιν ἵνα ποιῶ τὸ θέλημα τοῦ πέμψαντός με καὶ τελειώσω αὐτοῦ τὸ ἔργον. οὐχ ὑμεῖς λέγετε ὅτι Ἔτι τετράμηνός ἐστιν καὶ ὁ θερισμὸς ἔρχεται; ἰδοὺ λέγω ὑμῖν, ἐπάρατε τοὺς ὀφθαλμοὺς ὑμῶν καὶ θεάσασθε τὰς χώρας, ὅτι λευκαί εἰσιν πρὸς θερισμόν. ἤδη ὁ θερίζων μισθὸν λαμβάνει καὶ συνάγει καρπὸν εἰς ζωὴν αἰώνιον, ἵνα ὁ σπείρων ὁμοῦ χαίρῃ καὶ ὁ θερίζων. ἐν γὰρ τούτῳ ὁ λόγος ἐστὶν ἀληθινὸς ὅτι ἄλλος ἐστὶν ὁ σπείρων καὶ ἄλλος ὁ θερίζων. ἐγὼ ἀπέστειλα ὑμᾶς θερίζειν ὃ οὐχ ὑμεῖς κεκοπιάκατε· ἄλλοι κεκοπιάκασιν, καὶ ὑμεῖς εἰς τὸν κόπον αὐτῶν εἰσεληλύθατε. </p>

    <p>Ἐκ δὲ τῆς πόλεως ἐκείνης πολλοὶ ἐπίστευσαν εἰς αὐτὸν τῶν Σαμαρειτῶν διὰ τὸν λόγον τῆς γυναικὸς μαρτυρούσης ὅτι Εἶπέν μοι πάντα ἃ ἐποίησα. ὡς οὖν ἦλθον πρὸς αὐτὸν οἱ Σαμαρεῖται, ἠρώτων αὐτὸν μεῖναι παρ’ αὐτοῖς· καὶ ἔμεινεν ἐκεῖ δύο ἡμέρας. καὶ πολλῷ πλείους ἐπίστευσαν διὰ τὸν λόγον αὐτοῦ, τῇ τε γυναικὶ ἔλεγον ὅτι Οὐκέτι διὰ τὴν σὴν λαλιὰν πιστεύομεν· αὐτοὶ γὰρ ἀκηκόαμεν, καὶ οἴδαμεν ὅτι οὗτός ἐστιν ἀληθῶς ὁ Σωτὴρ τοῦ κόσμου.</p>

    <p>Μετὰ δὲ τὰς δύο ἡμέρας ἐξῆλθεν ἐκεῖθεν εἰς τὴν Γαλιλαίαν. αὐτὸς γὰρ Ἰησοῦς ἐμαρτύρησεν ὅτι προφήτης ἐν τῇ ἰδίᾳ πατρίδι τιμὴν οὐκ ἔχει. ὅτε οὖν ἦλθεν εἰς τὴν Γαλιλαίαν, ἐδέξαντο αὐτὸν οἱ Γαλιλαῖοι, πάντα ἑωρακότες ὅσα ἐποίησεν ἐν Ἱεροσολύμοις ἐν τῇ ἑορτῇ· καὶ αὐτοὶ γὰρ ἦλθον εἰς τὴν ἑορτήν. </p>

    <p>Ἦλθεν οὖν πάλιν εἰς τὴν Κανὰ τῆς Γαλιλαίας, ὅπου ἐποίησεν τὸ ὕδωρ οἶνον. Καὶ ἦν τις βασιλικὸς οὗ ὁ υἱὸς ἠσθένει ἐν Καφαρναούμ· οὗτος ἀκούσας ὅτι Ἰησοῦς ἥκει ἐκ τῆς Ἰουδαίας εἰς τὴν Γαλιλαίαν, ἀπῆλθεν πρὸς αὐτὸν καὶ ἠρώτα ἵνα καταβῇ καὶ ἰάσηται αὐτοῦ τὸν υἱόν· ἤμελλεν γὰρ ἀποθνήσκειν. εἶπεν οὖν ὁ Ἰησοῦς πρὸς αὐτόν Ἐὰν μὴ σημεῖα καὶ τέρατα ἴδητε, οὐ μὴ πιστεύσητε. λέγει πρὸς αὐτὸν ὁ βασιλικός Κύριε, κατάβηθι πρὶν ἀποθανεῖν τὸ παιδίον μου. λέγει αὐτῷ ὁ Ἰησοῦς Πορεύου· ὁ υἱός σου ζῇ. ἐπίστευσεν ὁ ἄνθρωπος τῷ λόγῳ ὃν εἶπεν αὐτῷ ὁ Ἰησοῦς, καὶ ἐπορεύετο. ἤδη δὲ αὐτοῦ καταβαίνοντος οἱ δοῦλοι ὑπήντησαν αὐτῷ λέγοντες ὅτι ὁ παῖς αὐτοῦ ζῇ. ἐπύθετο οὖν τὴν ὥραν παρ’ αὐτῶν ἐν ᾗ κομψότερον ἔσχεν· εἶπαν οὖν αὐτῷ ὅτι Ἐχθὲς ὥραν ἑβδόμην ἀφῆκεν αὐτὸν ὁ πυρετός. ἔγνω οὖν ὁ πατὴρ ὅτι ἐκείνῃ τῇ ὥρᾳ ἐν ᾗ εἶπεν αὐτῷ ὁ Ἰησοῦς Ὁ υἱός σου ζῇ· καὶ ἐπίστευσεν αὐτὸς καὶ ἡ οἰκία αὐτοῦ ὅλη. Τοῦτο δὲ πάλιν δεύτερον σημεῖον ἐποίησεν ὁ Ἰησοῦς ἐλθὼν ἐκ τῆς Ἰουδαίας εἰς τὴν Γαλιλαίαν.</p>
    </div>
  </div>

  <div class="column">
    <div class="article">
    <p>Hōs oun egnō ho Kyrios hoti ēkousan hoi Pharisaioi hoti Iēsous pleionas mathētas poiei kai baptizei ē Iōanēs, —kaitoige Iēsous autos ouk ebaptizen all’ hoi mathētai autou, — aphēken tēn Ioudaian kai apēlthen palin eis tēn Galilaian. Edei de auton dierchesthai dia tēs Samarias. erchetai oun eis polin tēs Samarias legomenēn Sychar, plēsion tou chōriou ho edōken Iakōb Iōsēph tō huiō autou; ēn de ekei pēgē tou Iakōb. ho oun Iēsous kekopiakōs ek tēs hodoiporias ekathezeto houtōs epi tē pēgē; hōra ēn hōs hektē. </p>

    <p>erchetai gynē ek tēs Samarias antlēsai hydōr. legei autē ho Iēsous Dos moi pein. hoi gar mathētai autou apelēlytheisan eis tēn polin, hina trophas agorasōsin. legei oun autō hē gynē hē Samareitis Pōs sy Ioudaios ōn par’ emou pein aiteis gynaikos Samareitidos ousēs? ou gar synchrōntai Ioudaioi Samareitais. apekrithē Iēsous kai eipen autē Ei ēdeis tēn dōrean tou Theou, kai tis estin ho legōn soi Dos moi pein, sy an ētēsas auton kai edōken an soi hydōr zōn. legei autō Kyrie, oute antlēma echeis kai to phrear estin bathy; pothen oun echeis to hydōr to zōn? mē sy meizōn ei tou patros hēmōn Iakōb, hos edōken hēmin to phrear, kai autos ex autou epien kai hoi huioi autou kai ta thremmata autou? apekrithē Iēsous kai eipen autē Pas ho pinōn ek tou hydatos toutou dipsēsei palin; hos d’ an piē ek tou hydatos hou egō dōsō autō, ou mē dipsēsei eis ton aiōna, alla to hydōr ho dōsō autō genēsetai en autō pēgē hydatos hallomenou eis zōēn aiōnion. legei pros auton hē gynē Kyrie, dos moi touto to hydōr, hina mē dipsō mēde dierchōmai enthade antlein. </p>

    <p>legei autē Hypage phōnēson ton andra sou kai elthe enthade. apekrithē hē gynē kai eipen Ouk echō andra. legei autē ho Iēsous Kalōs eipes hoti Andra ouk echō; pente gar andras esches, kai nyn hon echeis ouk estin sou anēr; touto alēthes eirēkas. legei autō hē gynē Kyrie, theōrō hoti prophētēs ei sy. hoi pateres hēmōn en tō orei toutō prosekynēsan; kai hymeis legete hoti en Hierosolymois estin ho topos hopou proskynein dei. legei autē ho Iēsous Pisteue moi, gynai, hoti erchetai hōra hote oute en tō orei toutō oute en Hierosolymois proskynēsete tō Patri. hymeis proskyneite ho ouk oidate, hēmeis proskynoumen ho oidamen, hoti hē sōtēria ek tōn Ioudaiōn estin; alla erchetai hōra kai nyn estin, hote hoi alēthinoi proskynētai proskynēsousin tō Patri en pneumati kai alētheia; kai gar ho Patēr toioutous zētei tous proskynountas auton; Pneuma ho Theos, kai tous proskynountas en pneumati kai alētheia dei proskynein. legei autō hē gynē Oida hoti Messias erchetai, ho legomenos Christos; hotan elthē ekeinos, anangelei hēmin hapanta. legei autē ho Iēsous Egō eimi, ho lalōn soi. </p>

    <p>Kai epi toutō ēlthan hoi mathētai autou, kai ethaumazon hoti meta gynaikos elalei; oudeis mentoi eipen Ti zēteis ē ti laleis met’ autēs? aphēken oun tēn hydrian autēs hē gynē kai apēlthen eis tēn polin, kai legei tois anthrōpois Deute idete anthrōpon hos eipen moi panta ha epoiēsa; mēti houtos estin ho Christos? exēlthon ek tēs poleōs kai ērchonto pros auton. En tō metaxy ērōtōn auton hoi mathētai legontes Rhabbei, phage. ho de eipen autois Egō brōsin echō phagein hēn hymeis ouk oidate. elegon oun hoi mathētai pros allēlous Mē tis ēnenken autō phagein? legei autois ho Iēsous Emon brōma estin hina poiō to thelēma tou pempsantos me kai teleiōsō autou to ergon. ouch hymeis legete hoti Eti tetramēnos estin kai ho therismos erchetai? idou legō hymin, eparate tous ophthalmous hymōn kai theasasthe tas chōras, hoti leukai eisin pros therismon. ēdē ho therizōn misthon lambanei kai synagei karpon eis zōēn aiōnion, hina ho speirōn homou chairē kai ho therizōn. en gar toutō ho logos estin alēthinos hoti allos estin ho speirōn kai allos ho therizōn. egō apesteila hymas therizein ho ouch hymeis kekopiakate; alloi kekopiakasin, kai hymeis eis ton kopon autōn eiselēlythate. </p>

    <p>Ek de tēs poleōs ekeinēs polloi episteusan eis auton tōn Samareitōn dia ton logon tēs gynaikos martyrousēs hoti Eipen moi panta ha epoiēsa. hōs oun ēlthon pros auton hoi Samareitai, ērōtōn auton meinai par’ autois; kai emeinen ekei dyo hēmeras. kai pollō pleious episteusan dia ton logon autou, tē te gynaiki elegon hoti Ouketi dia tēn sēn lalian pisteuomen; autoi gar akēkoamen, kai oidamen hoti houtos estin alēthōs ho Sōtēr tou kosmou.</p>

    <p>Meta de tas dyo hēmeras exēlthen ekeithen eis tēn Galilaian. autos gar Iēsous emartyrēsen hoti prophētēs en tē idia patridi timēn ouk echei. hote oun ēlthen eis tēn Galilaian, edexanto auton hoi Galilaioi, panta heōrakotes hosa epoiēsen en Hierosolymois en tē heortē; kai autoi gar ēlthon eis tēn heortēn. </p>

    <p>Ēlthen oun palin eis tēn Kana tēs Galilaias, hopou epoiēsen to hydōr oinon. Kai ēn tis basilikos hou ho huios ēsthenei en Kapharnaoum; houtos akousas hoti Iēsous hēkei ek tēs Ioudaias eis tēn Galilaian, apēlthen pros auton kai ērōta hina katabē kai iasētai autou ton huion; ēmellen gar apothnēskein. eipen oun ho Iēsous pros auton Ean mē sēmeia kai terata idēte, ou mē pisteusēte. legei pros auton ho basilikos Kyrie, katabēthi prin apothanein to paidion mou. legei autō ho Iēsous Poreuou; ho huios sou zē. episteusen ho anthrōpos tō logō hon eipen autō ho Iēsous, kai eporeueto. ēdē de autou katabainontos hoi douloi hypēntēsan autō legontes hoti ho pais autou zē. epytheto oun tēn hōran par’ autōn en hē kompsoteron eschen; eipan oun autō hoti Echthes hōran hebdomēn aphēken auton ho pyretos. egnō oun ho patēr hoti ekeinē tē hōra en hē eipen autō ho Iēsous HO huios sou zē; kai episteusen autos kai hē oikia autou holē. Touto de palin deuteron sēmeion epoiēsen ho Iēsous elthōn ek tēs Ioudaias eis tēn Galilaian.</p>
    </div>
  </div>

  <div class="column">
    <div class="article">
    <p>When the Lord, therefore, knew that the Pharisees had heard that Jesus was making and baptising more disciples than John — even tough Jesus did not baptise (them) himself —, he left Judea and left for Galilee. (In order to get there), he had to walk through Samaria. He went, then, to a city of Samaria called Sychar (which was) close to the region which Jacob gave to Joseph, his son; (and) there was a well of Jacob’s there (or Jacob’s Well). Jesus, therefore, having grown weary (tired) because of his journey, sat down upon the well (when the) time was approximately six (roughly noon).</p>

    <p>There (then) came a woman of Samaria (to the well) to draw (some) water (from it) and Jesus tells her, “Give me something to drink.” (He had to ask her) because his disciples left to go into the city to buy some food. The Samaritan woman then says to him, “How can you — being a Jew — ask for something to drink from me, a Samaritan woman? For (you know that) the Jews do not have dealings with the Samaritans.” Jesus answered and told her, “If you knew the gift of God and (if you knew) who was telling you: ‘give me something to drink’ — (if you really knew this) then you would have asked him (to give water to you) and he would have given you living water.” And the woman tells him, “(But) sir, you have nothing to draw water with and the well is deep; from where do you have living water (where did you get that living water of yours from)? Surely you are not greater than our father Jacob, who gave us this well and from which he himself — and his children and his livestock — have drunk?” Jesus answered and said to her, “Everyone who drinks from this water will be thirsty again (at some point); (but) whoever drinks from the water which I shall give them will not be thirsty again for eternity — instead, the water I shall give them will turn into a well within them, springing up into eternal life.” The woman says to him, “Sir, give me this water, so that I will never be thirsty again (and so that I will never have to) come here again to draw water.” </p>

    <p>He, then, says to her, “Get up, call your husband and come here (again).” The woman answered him and said, “I do not have a husband (man).” And Jesus tells her, “You said well that you have no husband (man). For you have had five husbands (men) (already), and he whom you now have is not (truly) your husband (man). This you said truthfully.” The woman tells him, “Sir, I (can) see that you are a prophet. Our fathers worshipped God in this mountain (Mount Gerizim), but you say that that the place to worship God is in Jerusalem.” Jesus tells her, “Believe me, woman, that the hour shall come in which you shall worship the Father neither in Jerusalem nor in this mountain. You worship that which you do not know, (but) we worship that which we know — for the salvation is from the Jews (i. e. The Messiah will be a Jew and not a Gentile or Samaritan). But the hour will come — and has already come — when the true worshippers will worship the Father in spirit and in truth; because the Father seeks such people to worship him. God is a spirit, and his worshippers must worship him in spirit and in truth.” And the woman tells him, “I know that the Messiah will come (which means ‘The Anointed One’); and when comes, he will tells us everything.” And Jesus tells her, “The one you are speaking of is I.”</p>

    <p>At this moment, his disciples arrived and they were amazed that he was speaking to a (the?) woman. But none of them asked (things such as): “What do you want?” or “Why are you speaking to her?” Leaving her water jar, she left for the city and told the people (there), “Come and see the man who told me all the things I have ever done. Is this not the Anointed One?” They left the city and went to him. In the meantime, his disciples were asking him saying, “Teacher, (please) eat.” He told them, “I have food to eat which you do not know of.” The disciples were saying to one another, “Has nobody brought him any food?” And Jesus says to them, “My food is doing the will of him who sent me and to finish his work. Did you not (once) say, ‘Only four months until harvest comes?’ Look, I tell you: lift up your eyes and see that the fields are already white for harvest. They who harvest will receive wages and gather fruit unto eternal life, so that the sower may rejoice together with the reaper. For in this the saying is true: ‘One sows and another reaps.’ I have sent you to reap that which you did not work for; others have laboured and you have been entered into their labour.”</p>

    <p>Many of the Samaritans from that city believed in him because of the woman’s testimony: “He told me all the things I have ever done”. When the Samaritans had walked to him, they asked him to stay with them — and he stayed there for two days. And many more believed (in him) because of his own words; and to the woman they said, “We no longer believe (in him) because of what you said; for we have heard ourselves, and we know (now) that he truly is the Saviour of the cosmos (world).”</p>

    <p>After the two days (had passed), he departed and left for Galilee. For Jesus himself testified that a prophet does not have any honour in his own homeland. As he arrived in Galilee, the Galileans welcomed him because they had seen all the things he had done at the feast; for they had gone to the feast themselves. </p>

    <p>Thus, he, once again, went to Cana of Galilee — (the place) where he had turned water to wine. And there was a royal official there, whose son was lying sick in Capernaum. He — having heard of Jesus’ coming from Judea to Galilee — went to Jesus and asked (him) if he could come down (to Capernaum) and heal his son — for he was about to die. Jesus, therefore, told him, “You do not believe unless you see signs and wonders?” And the royal official tells him, “Sir, (please) come down (to Capernaum) before my son’s death.” And Jesus tells him, “Go. Your son lives.” The man believed the words which Jesus had spoken to him and left. As he had gone down (and arrived), his servants met him and told him, “Your son lives.” He, then, inquired of them at which time he had gotten better; and they said, “His fever left him yesterday at seven (1 pm).” The father knew that it was during that hour in which Jesus told him, “Your son lives.” And he — and his entire family (household) — believed. This second sign Jesus did after coming from Judea and going into Galilee.</p>
    </div>
  </div>

</div>
</body>

<footer>
<?php include($_SERVER['DOCUMENT_ROOT'].'/footer.php'); ?>
</html>
